name: Release

permissions:
  contents: write
  packages: write
on:
  workflow_run:
    workflows: ["Go Test"]
    branches: [master]
    types:
      - completed
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: Arematics/workflows/.github/workflows/go-library-release.yml@master